sudo: required
services:
  - docker

before_install:
  - docker build -t jakubhav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jakubhav/react-test npm test
  # more tests can be added

after_success:
  - docker build -t jakubhav/multi-client ./client
  - docker build -t jakubhav/multi-nginx ./nginx
  - docker build -t jakubhav/multi-server ./server
  - docker build -t jakubhav/multi-worker ./worker

  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push jakubhav/multi-client
  - docker push jakubhav/multi-nginx
  - docker push jakubhav/multi-server
  - docker push jakubhav/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-470820610629'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY